import { Header } from '@/components/header/header';
import './globals.css';
import type { Metadata } from 'next';
import { BottomHeader } from '@/components/header/bottom-header';
import { Footer } from '@/components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='font-bodyFont'>
        <Header />
        <BottomHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
