import { Header } from '@/components/header/header';
import './globals.css';
import type { Metadata } from 'next';
import { BottomHeader } from '@/components/header/bottom-header';
import { Footer } from '@/components/footer';
import 'react-responsive-carousel/lib/styles/carousel.min.css'; // requires a loader
import { ReduxProvider } from '@/providers/redux-provider';
import AuthProvider from '@/providers/auth-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='font-bodyFont bg-gray-300'>
        <AuthProvider>
          <ReduxProvider>
            <Header />
            <BottomHeader />
            {children}
            <Footer />
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
